# Application settings
image:
  repository: ghcr.io/umar.fd/express-postgres-microservice
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# PostgreSQL settings
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: "mysecretpassword"
        database: "mydatabase"
        username: "postgres"
        password: "mysecretpassword"
  primary:
    persistence:
      enabled: true
      size: 1Gi
  service:
    port: 5432