{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "express-postgres.fullname" . }}-postgresql
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
  database: {{ .Values.postgresql.auth.database | b64enc }}
{{- end -}}