name: Helm Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Checkout semua history

      - name: Verify Chart Structure
        run: |
          echo "=== Struktur Direktori ==="
          ls -la
          echo "=== Isi Chart.yaml ==="
          cat Chart.yaml
          echo "=== Isi templates/ ==="
          ls -la templates/

          # Validasi ketat
          if [ ! -f "Chart.yaml" ]; then
            echo "::error::ERROR: Chart.yaml tidak ditemukan di root direktori"
            exit 1
          fi
          if [ ! -d "templates" ]; then
            echo "::error::ERROR: Folder templates tidak ditemukan"
            exit 1
          fi

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.0'

      - name: Lint Chart
        run: helm lint .

      - name: Package Chart
        run: |
          mkdir -p packaged-chart
          helm package . -d packaged-chart

      - name: Create Release
        run: |
          mkdir -p release-artifacts
          mv packaged-chart/*.tgz release-artifacts/
          helm repo index release-artifacts --url https://github.com/umarfd/express-postgres-chart/releases/download/v0.1.0/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: release-artifacts/
