name: Helm Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (full depth)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: 'src'  # Mengisolasi repo ke subfolder

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.0'

      - name: Debug Structure
        run: |
          echo "=== STRUKTUR DIREKTORI ==="
          ls -R src
          echo "=== ISI Chart.yaml ==="
          cat src/Chart.yaml
          echo "=== VALIDASI ==="
          [ -f "src/Chart.yaml" ] || (echo "ERROR: Chart.yaml tidak ditemukan" && exit 1)
          [ -d "src/templates" ] || (echo "WARNING: Folder templates tidak ditemukan")

      - name: Run Helm Lint
        run: |
          cd src
          helm lint . --strict

      - name: Package Chart
        run: |
          cd src
          mkdir -p ../packaged-chart
          helm package . -d ../packaged-chart

      - name: Create Release
        run: |
          mkdir -p release-artifacts
          mv packaged-chart/*.tgz release-artifacts/
          helm repo index release-artifacts --url https://github.com/umarfd/express-postgres-chart/releases/download/v0.1.0/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: release-artifacts/
