name: Helm Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Chart Structure
        run: |
          echo "Current directory structure:"
          ls -la
          if [ ! -f "Chart.yaml" ]; then
            echo "::error::Chart.yaml not found in root directory!"
            exit 1
          fi

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.0'

      - name: Run Helm Lint
        run: helm lint .

      - name: Package Helm Chart
        run: helm package . -d ./packaged-chart

      - name: Create Release Artifacts
        run: |
          mkdir -p ./release-artifacts
          mv ./packaged-chart/*.tgz ./release-artifacts/
          helm repo index ./release-artifacts --url https://github.com/umarfd/express-postgres-chart/releases/download/v0.1.0/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-release
          path: ./release-artifacts
